# Generated by Django 3.0.5 on 2020-08-01 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pprname', models.CharField(default='', max_length=100)),
                ('noofques', models.IntegerField(default=0)),
                ('question', models.CharField(default='', max_length=5000)),
                ('pprcode', models.CharField(default='', max_length=50)),
                ('pprteach', models.CharField(default='', max_length=100)),
                ('pdfop', models.CharField(default='', max_length=10)),
                ('starttime', models.DateTimeField(default=datetime.datetime.now)),
                ('endtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.AutoField(primary_key=True, serialize=False)),
                ('studname', models.CharField(default='', max_length=100)),
                ('studemail', models.EmailField(default='', max_length=100)),
                ('result', models.CharField(default='', max_length=100)),
                ('studrn', models.CharField(default='', max_length=100)),
                ('pprcode', models.CharField(default='', max_length=50)),
                ('studinst', models.CharField(default='', max_length=500)),
                ('subtime', models.CharField(default='', max_length=100)),
                ('pdf', models.FileField(default='', upload_to='ansside/pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('teachinclass', models.CharField(choices=[('Jr', 'Junior'), ('Md', 'Medium'), ('Sn', 'Senior')], max_length=3)),
                ('password', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
