# Generated by Django 3.0.5 on 2020-08-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0003_auto_20200801_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
