# Generated by Django 3.0.5 on 2020-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0004_question_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='review',
        ),
        migrations.AddField(
            model_name='student',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
