# Generated by Django 3.0.5 on 2020-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0005_auto_20200802_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teachinclass',
        ),
        migrations.AddField(
            model_name='teacher',
            name='review',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
