# Generated by Django 3.0.5 on 2020-08-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0008_teacher_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='student',
            name='result',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
