# Generated by Django 3.0.5 on 2020-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0009_auto_20200809_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='opt',
            field=models.CharField(default='', max_length=10),
        ),
    ]
