# Generated by Django 3.0.5 on 2020-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsite', '0011_auto_20200809_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactid', models.AutoField(primary_key=True, serialize=False)),
                ('contactname', models.CharField(default='', max_length=100)),
                ('contactemail', models.CharField(default='', max_length=100)),
                ('contactmsg', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
